// Routes
app.use('/api/blooms-taxonomy', bloomsTaxonomyRoutes);
app.use('/api/subjects', subRoutes);
app.use('/api/course-outcomes', courseOutcomeRoutes);
app.use('/api/subject-component-cos', subjectComponentCoRoutes);
app.use('/api/events', eventsRoutes);
app.use('/api/student-events', studentEventRoutes);
app.use('/api/event-outcomes', eventOutcomesRoutes);
app.use('/api/student-analysis', studentAnalysisRoutes);
app.use('/api/blooms-distribution', bloomsDistributionRoutes);